### ISSUE TITLE
Cannot contact you

### ISSUE THREAD

**Issue by bernd-wechner** [deanproxy/deanproxy.node#1]
The contact page at http://deanproxy.com/ is broken, and aside from that you're suitably hard to find ;-). You pushed to this repository a mere 30 mins ago though so that's a really good sign of life. I'd love to chat briefly if you'd give me time. Main interests:

http://deanproxy.com/blog/posts/2012/03/9-how-to-save-vpn-passwords-with-networkmanger.html

and your django work - I'm working with django and would love an ear for a pressing question - even though you're leaving django behind. Much depends on whether you want to have a quick chat with a Tasmanian about vpn configs in Network Manager and/or django.

**Comment by deanproxy** [comment]
Thanks. I didn't realize my contact form wasn't working any longer. 

What can I do for you?

**Comment by bernd-wechner** [comment]
Well, have you got an email address you can use? Or can you get the contact form working so I can share one? Or email me? I publish bwechner@yahoo.com on github as its the address I use for concentrating spam in ;-). I have even lower grade addresses for less trustworthy sites. If you emailed me there I could explain. But in summary:

1) Network manager not starting my VPN :-(
2) What were/are you using as an IDE for Django/Python?

But email is the place methinks not issues ...

**Comment by bernd-wechner** [comment]
Dean, now your site is completely down ;-). 

502 Bad Gateway
nginx/1.10.0 (Ubuntu)

Would love to hear from you.

**Comment by deanproxy** [comment]
Yeah, I'm working on the site.

As far as your VPN issue, I doubt I can help with that. For the IDE, I mainly use SublimeText or Atom. I'm not much of an IDE developer.  I have used IntelliJ for some Java stuff and found it to be helpful. I also tried PyCharm for a while. It's basically IntelliJ but stripped down for Python dev. It did a good job too. The debugger and merge tool are great selling points for it.

**Comment by bernd-wechner** [comment]
Good luck with the web site. I guess I'll have to find NetworkManager support somewhere else. Bizarre issue. I can run vpnc from bash and connect to my vpn. But Network Manager just reports "Error: Connection activation failed: the VPN service failed to start."

Here's what I wanted to write you:

I'm using vpnc.

I can connect with vpnc just fine, and trying to coax network manager into it before I bail from it (again). 

vpnc creates new network interface tun0 and all is good. I can connect and disconnect just fine. Sweet. 

It's config file /etc/vpnc/default.conf is (I'll use three letter upper case codes for privacy masked fields in this post and to illustrate the mapping to the Network Manager config file):

$ cat /etc/vpnc/default.conf 
IPSec gateway III
IPSec ID AAA
IPSec secret BBB
Xauth username CCC
Xauth password DDD

Now I am trying to configure network manager so I use it's neat system tray interface. And here is the analagous nm file:

$ cat /etc/NetworkManager/system-connections/AAA
[connection]
id=AAA
uuid=386ef8c6-d660-4892-b74b-50efdd47bd24
type=vpn
autoconnect=false
permissions=user:bernd:;
secondaries=

[vpn]
NAT Traversal Mode=natt
ipsec-secret-type=save
IPSec secret-flags=0
xauth-password-type=save
Vendor=cisco
Xauth username=CCC
IPSec gateway=III
Xauth password-flags=0
IPSec ID=AAA
Perfect Forward Secrecy=server
IKE DH Group=dh2
Local Port=0
service-type=org.freedesktop.NetworkManager.vpnc

[vpn-secrets]
Xauth password=DDD
IPSec secret=BBB

[ipv4]
dns-search=
method=auto

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
ip6-privacy=0
method=auto

But alas:

$ nmcli con up AAA
Error: Connection activation failed: the VPN service failed to start.

ditto:

$ sudo nmcli con up AAA
Error: Connection activation failed: the VPN service failed to start.

I admit I find the Network Manager a pain. What can be causing this? 

If perchance you have a clue, I'd be pleased as a bit of on-line research has found no better page than yours above alas.
